# Generated by Django 5.0.2 on 2024-05-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('senha', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
