# Generated by Django 5.0 on 2024-06-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('senha', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_perfil', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.fotoperfil')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoInstrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=4)),
                ('instrutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.instrutor', verbose_name='instrutor')),
            ],
        ),
    ]
