# Generated by Django 4.2.13 on 2024-06-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_instrutor_codigoinstrutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrutor',
            name='foto_perfil',
        ),
        migrations.DeleteModel(
            name='CodigoInstrutor',
        ),
        migrations.DeleteModel(
            name='Instrutor',
        ),
    ]
