# Generated by Django 4.2.13 on 2024-06-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_instrutor_foto_perfil_delete_codigoinstrutor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('senha', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_perfil', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.fotoperfil')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoInstrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=4)),
                ('instrutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.instrutor', verbose_name='instrutor')),
            ],
        ),
    ]
