# Generated by Django 5.0 on 2024-06-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0003_rename_video_aula_url_aula_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='estacoes.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estacao',
            field=models.ManyToManyField(related_name='cursos', to='estacoes.estacao'),
        ),
    ]
